### ISSUE TITLE
Need SetHero command

### ISSUE THREAD

**Issue by Arhowk** [Arhowk/Banjoball#14]
The hero selection works by defaulting everyone with Enigma than replacing them later.

The game code doesn't like this.

Gimme some way to switch the hero plz dayne

(also cool for repick support)

**Comment by CarpeSwag** [comment]
I guess I'll look into this. If we did then we'd also need to enable player team swaps.

**Comment by Arhowk** [comment]
need? no.

could do? yes.

**Comment by CarpeSwag** [comment]
Yeah posted that comment then realized its not so much of a need. 

Anyways I'll get on this after curveshot and mana changes. I've been putting it off for too long anyways.

**Comment by Arhowk** [comment]
still need

**Comment by CarpeSwag** [comment]
Should work atm, but right now the dead heroes are still physics objects. I'll fix that and then it'll be perf.

**Comment by CarpeSwag** [comment]
Should be functional.
