### ISSUE TITLE
Thing i need

### ISSUE THREAD

**Issue by Arhowk** [Arhowk/Banjoball#17]
I need a picture of the field for the minimap. i odnt want to use the default picture because ti has extra space on the top and the bottom.

**Comment by CarpeSwag** [comment]
Do you mean the one I have currently in game?
![image](https://cloud.githubusercontent.com/assets/10646605/11998309/dc0d1dfe-aa5e-11e5-9a15-a2ef8ac469e0.png)

**Comment by Arhowk** [comment]
Cut off everything besides the rectangle field. Since the goal box can't be entered by anyone besides the goalie, I'll just render him inside of the goal box if he goes in the box

**Comment by CarpeSwag** [comment]
Aight. I'll have that and #14 done by the time I get back from the cruise. I may even possibly have internet on my cruise, so I might be able to push it sometime during the week.

**Comment by Arhowk** [comment]
meh ill just shop that image out.

i also need some sort of border for it

**Comment by CarpeSwag** [comment]
Nah fam I gotchu:
![image](https://cloud.githubusercontent.com/assets/10646605/12156336/5208dd70-b47f-11e5-9d12-469b003bc3b0.png)
https://www.dropbox.com/s/6j04xjnd8ce65hc/sunny_field.tga?dl=0
