### ISSUE TITLE
Hero sizes and speeds

### ISSUE THREAD

**Issue by CarpeSwag** [Arhowk/Banjoball#4]
I think we should reduce hero size by 80% and (maybe) hero speed to 300. I don't think it'll have a negative effect on gameplay as no one dribbles the whole field, and if they do, it'll probably have a marginal effect on the game.

The goal would be to make the goal boxes feel a bit wider without actually touching the map or the mess of constants that are within it.

**Comment by Arhowk** [comment]
For the hero box, you could just apply some ms effect on the goalie, so it doesn't slow down the pace of gameplay (albeit minimally)

**Comment by CarpeSwag** [comment]
Eh maybe that could work. Though it kinda kills consistency.

**Comment by CarpeSwag** [comment]
I already take this back. 100% back. I'm just going to close this issue and pretend I never suggested it.
